language:
    - objective-c
    
compiler:
    - clang
    
before_install:
    - brew update

install:
    - brew install cmake

before_script:
    - export POLLY_ROOT=`pwd`
    - git clone --depth=1 https://github.com/ruslo/gitenv
    - export GITENV_ROOT=`pwd`/gitenv
    - cd gitenv
    - git submodule update --init llvm/libcxx sugar
    - git submodule foreach 'git checkout master && git pull'
    - cd llvm/libcxx
    - mkdir _builds
    - (cd _builds/ && rm -rf * && cmake -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/CustomLibcxx.cmake -DLIBCXX_ENABLE_SHARED=OFF -DCMAKE_BUILD_TYPE=Debug .. && make VERBOSE=1 install)
    - (cd _builds/ && rm -rf * && cmake -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/CustomLibcxx.cmake -DLIBCXX_ENABLE_SHARED=OFF -DCMAKE_BUILD_TYPE=Release .. && make VERBOSE=1 install)
    - ls _install/custom_libcxx/lib/*.a
    
script:
    - pwd
