language:
    - objective-c

env:
    # 01
    - EXAMPLE=01-executable TOOLCHAIN=default CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=default CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=libcxx CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=libcxx CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=clang-libstdcxx CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=clang-libstdcxx CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=xcode CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=xcode CONFIG=Relese
    - EXAMPLE=01-executable TOOLCHAIN=gcc CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=gcc CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=ios-nocodesign CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=ios-nocodesign CONFIG=Release
    - EXAMPLE=01-executable TOOLCHAIN=analyze CONFIG=Debug
    - EXAMPLE=01-executable TOOLCHAIN=analyze CONFIG=Release
    # 02
    - EXAMPLE=02-library TOOLCHAIN=default CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=default CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=libcxx CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=libcxx CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=clang-libstdcxx CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=clang-libstdcxx CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=xcode CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=xcode CONFIG=Relese
    - EXAMPLE=02-library TOOLCHAIN=gcc CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=gcc CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=ios-nocodesign CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=ios-nocodesign CONFIG=Release
    - EXAMPLE=02-library TOOLCHAIN=analyze CONFIG=Debug
    - EXAMPLE=02-library TOOLCHAIN=analyze CONFIG=Release
    # 03
    - EXAMPLE=03-shared-link TOOLCHAIN=default CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=default CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=libcxx CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=libcxx CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=clang-libstdcxx CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=clang-libstdcxx CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=xcode CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=xcode CONFIG=Relese
    - EXAMPLE=03-shared-link TOOLCHAIN=gcc CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=gcc CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=ios-nocodesign CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=ios-nocodesign CONFIG=Release
    - EXAMPLE=03-shared-link TOOLCHAIN=analyze CONFIG=Debug
    - EXAMPLE=03-shared-link TOOLCHAIN=analyze CONFIG=Release

install:
    - brew install python3
    - brew install cmake
    # install cmake
    - CMAKE_VERSION="3.0.2-ios-universal"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    -   cmake -H. -B_builds -DCMAKE_INSTALL_PREFIX="`pwd`/_install/" -DCMAKE_BUILD_TYPE=Release -DCMAKE_USE_SYSTEM_CURL=YES
    -   cmake --build _builds --target install
    -   export PATH="`pwd`/_install/bin:${PATH}"
    - cd ..
    # -- end

script:
    - which cmake
    - python3 ./examples/jenkins.py
