language:
    - objective-c

env:
    - EXAMPLE=00-simple TOOLCHAIN=Libcxx
    - EXAMPLE=00-simple TOOLCHAIN=Libstdcxx
    - EXAMPLE=01-executable TOOLCHAIN=Default
    - EXAMPLE=01-executable TOOLCHAIN=Libcxx
    - EXAMPLE=01-executable TOOLCHAIN=Libstdcxx
    - EXAMPLE=01-executable TOOLCHAIN=CustomLibcxx
    - EXAMPLE=02-library TOOLCHAIN=Default
    - EXAMPLE=02-library TOOLCHAIN=Libcxx
    - EXAMPLE=02-library TOOLCHAIN=Libstdcxx
    - EXAMPLE=02-library TOOLCHAIN=CustomLibcxx
    - EXAMPLE=02-library GENERATOR=-GXcode TOOLCHAIN=iOS

compiler:
    - clang

before_install:
    - brew update
    - export POLLY_ROOT=`pwd`

install:
    - brew install cmake
    - brew install wget
    # install custom libcxx --
    - mkdir custom_libcxx_lib
    - cd custom_libcxx_lib
    - export LIBCXX_ROOT=`pwd`/Install
    - git clone http://llvm.org/git/libcxx .
    - mkdir _builds
    - cd _builds
    # release
    - cmake -DCMAKE_INSTALL_PREFIX=${LIBCXX_ROOT} -DLIBCXX_ENABLE_SHARED=OFF -DCMAKE_BUILD_TYPE=Release -DLIBCXX_ENABLE_ASSERTIONS=OFF ..
    - make VERBOSE=1 install
    - rm -rf *
    # debug
    - cmake -DCMAKE_INSTALL_PREFIX=${LIBCXX_ROOT} -DLIBCXX_ENABLE_SHARED=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DEBUG_POSTFIX=d ..
    - make VERBOSE=1 install
    - ls -la ${LIBCXX_ROOT}/lib/*
    # -- end
    # download sugar for 02-library example
    - wget https://github.com/ruslo/sugar/archive/v1.0.0.tar.gz
    - tar xf *.tar.gz
    - export SUGAR_ROOT=`pwd`/sugar-*
    # -- end

script:
    - cd ${POLLY_ROOT}/examples/${EXAMPLE}
    - mkdir _builds
    - cd _builds
    # release
    - cmake ${GENERATOR} -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/${TOOLCHAIN}.cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
    - ctest -V .
    - cmake --build . -target install
    # debug
    - rm -rf *
    - cmake ${GENERATOR} -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/${TOOLCHAIN}.cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build .
    - ctest -V .
    - cmake --build . -target install
