language:
    - objective-c

env:
    - EXAMPLE=00-simple TOOLCHAIN=Libcxx
    - EXAMPLE=00-simple TOOLCHAIN=Libstdcxx

compiler:
    - clang

before_install:
    - brew update

install:
    - brew install cmake
    - brew install wget

before_script:
    - export POLLY_ROOT=`pwd`

script:
    - cd ${POLLY_ROOT}/examples/${EXAMPLE}
    - mkdir _builds
    - cd _builds
    - cmake -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/${TOOLCHAIN}.cmake ..
    - cmake --build .
